### ISSUE TITLE
Update an IPv4 Access Rule

### ISSUE THREAD

**Issue by EtienneMILON** [Forcepoint/fp-NGFW-SMC-python#17]
Hello,

I try to update an IPv4 Access Rule. It doesn't work with rule.update() method or rule.save() method.
Is it possible to update a rule?
I use fp-NGFW-SMC-python==0.7.0b26 and SMC 6.5.17.

With update method and host object or href of host object :
```
policy = FirewallPolicy("policy_name")
rule = list(policy.fw_ipv4_access_rules)[-1]
one_host = Host("host_name")
rule.update(sources=[one_host])
rule.update(sources=[one_host.href])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python37\lib\site-packages\smc\policy\rule.py", line 290, in update
    result = super(Rule, self).update(PolicyCommandFailed, **kwargs)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python37\lib\site-packages\smc\base\model.py", line 494, in update
    result = request.update()
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python37\lib\site-packages\smc\api\common.py", line 72, in update
    return self._make_request(method='PUT')
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python37\lib\site-packages\smc\api\common.py", line 101, in _make_request
    raise err
smc.api.exceptions.PolicyCommandFailed: Invalid JSON format: Cannot deserialize instance of `com.stonesoft.api.v11.elements.dto.storable.policy.SrcMatchPartDTO` out of START_ARRAY token at [line: 1, column: 1558] (from: FWIPv4AccessRuleDTO["sources"]).
```

With save method:
```
rule.sources.src = [one_host.href]
rule.save()
rule.sources.src
>>> list of href before change
```

Best regards,
Etienne MILON

**Comment by ggrimaux** [comment]
Hello,

We are internally checking it. We can reproduce the problem so now we need to understand what is the problem.

BR,
/Greg

**Comment by ggrimaux** [comment]
So we found a way to make it works

`rule.update(sources={"src": [one_host.href]})`

But that could be done in another way. We are still checking what we can do.

BR,
/Greg

**Comment by ggrimaux** [comment]
So it is also working with rule.save()

```
print(rule.sources.src)
one_host = Host("Host3")
rule.sources.data['src'] = [one_host.href]
print(rule.sources.src)
rule.save()

```

Maybe not perfect but we'll see if we can do some improvement on this area :).

We hope it is unblocking you.

BR,
/Greg

**Comment by thomasdevulder** [comment]
created issue : issues/49 on enterprise github

**Comment by EtienneMILON** [comment]
Hello,

I confirm that it works with rule.update() and the good dict.

Do you think it could be possible to change the rule data structure?
I mean for "sources", "destinations", "services", and also maybe for "action" and "options".
It is not practical to use the structure with "src", "dst", "service" or "any: True".

Etienne

**Comment by ggrimaux** [comment]
@thomasdevulder created an issue for that :)
