### ISSUE TITLE
Issue with MultilinkMember.create in SMC 6.8

### ISSUE THREAD

**Issue by fgazelot** [Forcepoint/fp-NGFW-SMC-python#19]
Hello,

I'm working on the migration to my script worked on SMC 6.5 to SMC 6.8 and make the switch from  "smc-python" to "fp-NGFW-SMC-python" at the same time.

When i try to create my MultilinkMember for my Multilink, i have this issue : 
```
Traceback (most recent call last):
  File "test-oml.py", line 46, in <module>
    create_multilinks()
  File "test-oml.py", line 26, in create_multilinks
    l_ml_member.extend(MultilinkMember.create(netlink=snl1, netlink_role='active', ip_range='6.1.1.1-6.1.1.254'))
  File "/home/fgt/Documents/newlode/dev/ats-test-68/atsRunSdwan/env/lib/python3.8/site-packages/smc/elements/netlink.py", line 523, in create
    member_def.update(network_ref=netlink.network[0].href)
IndexError: list index out of range
```

I have created a little script to create the issue, on this script i have this function :

```
def create_multilinks():

    snl1 = list(Search.objects.all().filter('SNL_Premier-ISP'))[0]
    snl2 = list(Search.objects.all().filter('SNL_Second-ISP'))[0]
    l_ml_member = list()
    print('SNL1\n', snl1.data.data)
    print('SNL2\n', snl2.data.data)

    print('SNL1.network\n', snl1.network)
    print('SNL2.network\n', snl2.network)

    l_ml_member.extend(MultilinkMember.create(netlink=snl1, netlink_role='active', ip_range='6.1.1.1-6.1.1.254'))
    l_ml_member.extend(MultilinkMember.create(netlink=snl2, netlink_role='standby', ip_range='1.1.2.1-1.1.2.254'))

    res = Multilink.update_or_create(with_status=True,
                                     name="OML_TEST",
                                     multilink_members=l_ml_member)

    return res 
```

The output of my print : 

```
SNL1
 {'active_mode_period': 5, 'active_mode_timeout': 1, 'domain_server_address': [], 'gateway_ref': 'http://X.X.X.X:8082/6.5/elements/router/7249', 'key': 7250, 'link': [{'href': 'http://X.X.X.X8082/6.5/elements/netlink/7250', 'rel': 'self', 'type': 'netlink'}, {'href': 'http://X.X.X.X.68:8082/6.5/elements/netlink/7250/export', 'rel': 'export'}, {'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7250/history', 'rel': 'history'}, {'href': 'http://X.X.X.X8082/6.5/elements/netlink/7250/search_category_tags_from_element', 'rel': 'search_category_tags_from_element'}, {'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7250/duplicate', 'rel': 'duplicate'}], 'name': 'SNL_Premier-ISP', 'nsp_name': '', 'probe_address': [], 'read_only': False, 'ref': ['http:/X.X.X.X:8082/6.5/elements/network/7243'], 'standby_mode_period': 3600, 'standby_mode_timeout': 30, 'system': False, 'system_key': -1}

SNL2
 {'active_mode_period': 5, 'active_mode_timeout': 1, 'domain_server_address': [], 'gateway_ref': 'http://X.X.X.X :8082/6.5/elements/router/7252', 'key': 7253, 'link': [{'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7253', 'rel': 'self', 'type': 'netlink'}, {'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7253/export', 'rel': 'export'}, {'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7253/history', 'rel': 'history'}, {'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7253/search_category_tags_from_element', 'rel': 'search_category_tags_from_element'}, {'href': 'http://X.X.X.X:8082/6.5/elements/netlink/7253/duplicate', 'rel': 'duplicate'}], 'name': 'SNL_Second-ISP', 'probe_address': [], 'read_only': False, 'ref': ['http://X.X.X.X:8082/6.5/elements/network/7246'], 'standby_mode_period': 3600, 'standby_mode_timeout': 30, 'system': False, 'system_key': -1}

SNL1.network
 []
SNL2.network
 []

SNL1.ref
 ['http://X.X.X.X:8082/6.5/elements/network/7243']
SNL2.ref
 ['http://X.X.X.X:8082/6.5/elements/network/7246']

```

With the error, we can see in line 523 in "smc/elements/netlink.py"  we try to get the ref of the network in the SNL with "network_ref=netlink.network[0].href", but you can see with my print the "snl.network" is empty and the ref wanted is on "snl.ref".

I have created the SNL with SMC, with python, with ansible and the result is all time the same -> snl.netwotk is empty
I tried to make snl.ref = snl.network and snl.update() but same result... 

All work's correctly with this changeat line 523 : 

```
        if netlink.typeof == 'netlink':  # static netlink vs dynamic netlink
            #member_def.update(network_ref=netlink.network[0].href)
            member_def.update(network_ref=str(netlink.ref))
```

Information of my environement  : 

```
In [8]: session.manager.sessions[0].api_version
Out[8]: '6.5'

pip list | grep SMC                                                                                                                                                               
fp-NGFW-SMC-python 1.0.0    
```
I don't know if the issue is only in my environment.

Thank you in advance for your help.

Kind regards,
Fgazelot

**Comment by thomasdevulder** [comment]
Hello Fgazelot,

I tried to reproduce using SMC6.10 and Api 6.10 for me it works fine..
I am going to reproduce in SMC6.8 and Api 6.5 .....

my example script:

```python
"""
Example script to show how to use Multilink
"""

# Python Base Import
import sys
from smc import session
from smc.elements.netlink import StaticNetlink, MultilinkMember, Multilink

if __name__ == '__main__':
    URLSMC='http://localhost:8082'
    APIKEYSMC='HuphG4Uwg4dN6TyvorTR0001'
    try:
        session.login(url=URLSMC, api_key=APIKEYSMC, verify=False, timeout=120, api_version='6.10')
    except BaseException as exception_retournee:
        sys.exit(-1)

    print("session OK")
try:
    # create multi link
    snl1 = StaticNetlink.create(name="SNL_Premier-ISP",
                                provider_name="ISP1",
                                output_speed=40000,
                                input_speed=40000,
                                probe_address=["10.1.16.1"],
                                network=["http://localhost:8082/6.10/elements/network/1684"],
                                gateway="http://localhost:8082/6.10/elements/router/1682",
                                connection_type="http://localhost:8082/6.10/elements/connection_type/1",
                                )
    snl2 = StaticNetlink.create(name="SNL_Second-ISP",
                                provider_name="ISP2",
                                output_speed=50000,
                                input_speed=50000,
                                probe_address=["172.31.16.1"],
                                network=["http://localhost:8082/6.10/elements/network/1678"],
                                gateway="http://localhost:8082/6.10/elements/router/1676",
                                connection_type="http://localhost:8082/6.10/elements/connection_type/1",
                                )

    print('SNL1\n', snl1.data.data)
    print('SNL2\n', snl2.data.data)

    print('SNL1.network\n', snl1.network)
    print('SNL2.network\n', snl2.network)
    l_ml_member = list()
    l_ml_member.append(MultilinkMember.create(netlink=snl1, netlink_role='active', ip_range='10.1.16.1-10.1.16.254'))
    l_ml_member.append(MultilinkMember.create(netlink=snl2, netlink_role='standby', ip_range='172.31.16.1-172.31.16.254'))

    oml = Multilink.create(name="OML_TEST",
                           multilink_members=l_ml_member)
    print('oml={} members={}'.format(str(oml), oml.members))
except Exception as e:
    print(e)
finally:
    oml = Multilink.get(name="OML_TEST")
    oml.delete()
    snl1 = StaticNetlink.get(name="SNL_Premier-ISP")
    snl1.delete()
    snl2 = StaticNetlink.get(name="SNL_Second-ISP")
    snl2.delete()
    session.logout()
```

return:
```
session OK
SNL1
 {'active_mode_period': 5, 'active_mode_timeout': 1, 'connection_type_ref': 'http://localhost:8082/6.10/elements/connection_type/1', 'domain_server_address': [], 'gateway_ref': 'http://localhost:8082/6.10/elements/router/1682', 'input_speed': 40000, 'key': 4372, 'link': [{'href': 'http://localhost:8082/6.10/elements/netlink/4372', 'rel': 'self', 'type': 'netlink'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4372/export', 'rel': 'export'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4372/history', 'rel': 'history'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4372/search_category_tags_from_element', 'rel': 'search_category_tags_from_element'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4372/duplicate', 'rel': 'duplicate'}], 'name': 'SNL_Premier-ISP', 'network_ref': ['http://localhost:8082/6.10/elements/network/1684'], 'nsp_name': 'ISP1', 'output_speed': 40000, 'probe_address': ['10.1.16.1'], 'read_only': False, 'standby_mode_period': 3600, 'standby_mode_timeout': 30, 'system': False, 'system_key': -1}
SNL2
 {'active_mode_period': 5, 'active_mode_timeout': 1, 'connection_type_ref': 'http://localhost:8082/6.10/elements/connection_type/1', 'domain_server_address': [], 'gateway_ref': 'http://localhost:8082/6.10/elements/router/1676', 'input_speed': 50000, 'key': 4373, 'link': [{'href': 'http://localhost:8082/6.10/elements/netlink/4373', 'rel': 'self', 'type': 'netlink'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4373/export', 'rel': 'export'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4373/history', 'rel': 'history'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4373/search_category_tags_from_element', 'rel': 'search_category_tags_from_element'}, {'href': 'http://localhost:8082/6.10/elements/netlink/4373/duplicate', 'rel': 'duplicate'}], 'name': 'SNL_Second-ISP', 'network_ref': ['http://localhost:8082/6.10/elements/network/1678'], 'nsp_name': 'ISP2', 'output_speed': 50000, 'probe_address': ['172.31.16.1'], 'read_only': False, 'standby_mode_period': 3600, 'standby_mode_timeout': 30, 'system': False, 'system_key': -1}
SNL1.network
 [Network(name=net-10.1.16.0/24)]
SNL2.network
 [Network(name=net-172.31.16.0/24)]
oml=Multilink(name=OML_TEST) members=[MultilinkMember(netlink=StaticNetlink(name=SNL_Premier-ISP),netlink_role=active,ip_range=10.1.16.1-10.1.16.254), MultilinkMember(netlink=StaticNetlink(name=SNL_Second-ISP),netlink_role=standby,ip_range=172.31.16.1-172.31.16.254)]

Process finished with exit code 0
```

**Comment by thomasdevulder** [comment]
I could reproduce the issue using SMC 6.8.5 and Api v6.5
```
SNL1
 {'active_mode_period': 5, 'active_mode_timeout': 1, 'domain_server_address': [], 'gateway_ref': 'http://localhost:8082/6.5/elements/router/1682', 'input_speed': 40000, 'key': 4054, 'link': [{'href': 'http://localhost:8082/6.5/elements/netlink/4054', 'rel': 'self', 'type': 'netlink'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4054/export', 'rel': 'export'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4054/history', 'rel': 'history'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4054/search_category_tags_from_element', 'rel': 'search_category_tags_from_element'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4054/duplicate', 'rel': 'duplicate'}], 'name': 'SNL_Premier-ISP', 'nsp_name': 'ISP1', 'output_speed': 40000, 'probe_address': ['10.1.16.1'], 'read_only': False, 'ref': ['http://localhost:8082/6.5/elements/network/1684'], 'standby_mode_period': 3600, 'standby_mode_timeout': 30, 'system': False, 'system_key': -1}
SNL2
 {'active_mode_period': 5, 'active_mode_timeout': 1, 'domain_server_address': [], 'gateway_ref': 'http://localhost:8082/6.5/elements/router/1676', 'input_speed': 50000, 'key': 4055, 'link': [{'href': 'http://localhost:8082/6.5/elements/netlink/4055', 'rel': 'self', 'type': 'netlink'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4055/export', 'rel': 'export'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4055/history', 'rel': 'history'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4055/search_category_tags_from_element', 'rel': 'search_category_tags_from_element'}, {'href': 'http://localhost:8082/6.5/elements/netlink/4055/duplicate', 'rel': 'duplicate'}], 'name': 'SNL_Second-ISP', 'nsp_name': 'ISP2', 'output_speed': 50000, 'probe_address': ['172.31.16.1'], 'read_only': False, 'ref': ['http://localhost:8082/6.5/elements/network/1678'], 'standby_mode_period': 3600, 'standby_mode_timeout': 30, 'system': False, 'system_key': -1}
SNL1.network
 []
SNL2.network
 []
```

I open an issue in GitHub Enterprise and make the fix in order to retrieve correctly network field..

Thanks.

**Comment by fgazelot** [comment]
Hello,

Thank you for taking the time to check.

I'm waiting for a fix then :)

Thanks,
Fgazelot

**Comment by fgazelot** [comment]
Hello thomasdevulder, 

I hope all is well.

Do you have any update for me about the issue in GitHub Enterprise ? 

Kind regards,
FGazelot

**Comment by thomasdevulder** [comment]
Hello,
this issue was a more general issue related to get_best_version method and was fixed and merged in our GitHub Enterprise.
It will be published to GitHub.com in next release, I think next week.

**Comment by fgazelot** [comment]
Hello thomasdevulder,

Thanks for this fix !
Kind regards,
FGazelot
