### ISSUE TITLE
rule_counters no valid message returned

### ISSUE THREAD

**Issue by jondyx** [Forcepoint/fp-NGFW-SMC-python#24]
Hello,
i am working on a programm that saves all the rules with name, source, destination, service and hits in a csv. When i try the function rule_counter = policy.rule_counters(engine, duration_type="one_week", duration=0) i get the error massage:

Traceback (most recent call last):
  File "C:\Users\...\Documents\SMC\halbjaehrliche-fw-regelabfrage\Regelset auslesen\Abfrage.py", line 651, in <module>
    main()
  File "C:\Users\...\Documents\SMC\halbjaehrliche-fw-regelabfrage\Regelset auslesen\Abfrage.py", line 463, in main
    rule_counter = policy.rule_counters(engine, duration_type="one_week", duration=0)
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\smc\policy\policy.py", line 154, in rule_counters
    for rule in self.make_request(method="create", resource="rule_counter", json=json)
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\smc\base\mixins.py", line 32, in make_request
    result = getattr(request, method)()
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\smc\api\common.py", line 76, in create
    return self._make_request(method="POST")
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\smc\api\common.py", line 110, in _make_request
    raise err
smc.api.exceptions.ActionCommandFailed: No valid message returned from SMC server

can you help? We need the hit number to show if a rule is usefull.

**Comment by ggrimaux** [comment]
Hello,

It looks like an error on server side. You should check if there is an error on server side.

I did a quick test and it is working so it could be specific to your backup or your SMC version.

/Greg.

**Comment by jondyx** [comment]
Thanks for your answer. 
On the server i can see the hits. But if i try to get the hits via SMC Api the error occurs. Is there a way the see how the not valid massage is look like? 

Using SMC API version: 6.5

**Comment by ggrimaux** [comment]
Which SMC version please? Can you paste the server error here also please?

**Comment by jondyx** [comment]
SMC Version 6.8.7 [10939], There might be a missunderstanding. There is no Server Error.

**Comment by jondyx** [comment]
Thanks for the location.

Error is: M!Impossible to execute a rule counter operation on the policy Policy-4204-Inst-1

**Comment by ggrimaux** [comment]
Can you paste full stack trace please?

**Comment by jondyx** [comment]
E!com.stonesoft.api.server ERROR [2021-11-23 13:48:02,885] [https-jsse-nio-8082-exec-5] [[UW:5:21: jd_api, TX]] {DB=SMC_API}
M!Impossible to execute a rule counter operation on the policy Policy-4204-Inst-1.
com.stonesoft.h2a.statistics.elements.NoRuleCountersFoundException
        at com.stonesoft.h2a.api.b.a1.i(a1.java:2)
        at com.stonesoft.h2a.api.b.a1.d(a1.java:43)
        at com.stonesoft.u.a.c(a.java:4)
        at com.stonesoft.h2a.mgtserver.persistency.aw.a(aw.java:75)
        at com.stonesoft.h2a.persistency.ab.a(ab.java:99)
        at com.stonesoft.api.a.a(a.java:8)
        at com.stonesoft.api.v11.elements.PolicyRuleCounterLinks.computeRuleCounters(PolicyRuleCounterLinks.java:49)
        at com.stonesoft.api.v11.elements.PolicyRuleCounterLinks$Proxy$_$$_WeldClientProxy.computeRuleCounters(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor5164.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
        at com.stonesoft.api.server.servlet.SMCAPIRESTServlet.service(SMCAPIRESTServlet.java:33)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.stonesoft.api.v11.filter.SMCAPIValidationFilter.doFilter(SMCAPIValidationFilter.java:24)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.stonesoft.api.server.filter.SMCAPILoggingFilter.doFilter(SMCAPILoggingFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.stonesoft.api.server.filter.SMCAPIDOSLoggerFilter.doFilter(SMCAPIDOSLoggerFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ggrimaux** [comment]
Thanks I'll check with one developer and I'll let you know what to do next.

**Comment by ggrimaux** [comment]
It is working fine in GUI when you do ask for rule hits?

**Comment by jondyx** [comment]
Little Exampel:

After Logging in:

engine = Engine("4204-Inst-1")  #Layer3VirtualEngine
policy=FirewallPolicy.get("Policy-4204-Inst-1")
rule_counter = policy.rule_counters(engine, duration_type="one_week", duration=0)
for counter in rule_counter:
    if rule_tag in counter.rule.name:
        print("hits")
        print(counter)

**Comment by thomasdevulder** [comment]
Fix included in smc-python 1.0.13

**Comment by jondyx** [comment]
Danke, Fehlermeldung verschwindet mit dem Fix
