### ISSUE TITLE
fw_ipv4_access_rules.create() does not accept correct action

### ISSUE THREAD

**Issue by shibumi** [Forcepoint/fp-NGFW-SMC-python#3]
Hi @gabstopper,

I've encountered the following bug while playing around with the API.

smc python version: 0.6.2 (according to `pip freeze`)

Last debug output:

```
Response status: 200
Response headers:
        'ETag': '"NTQ4NDk5OWViNDVlZTdhYTY4ODliODFlOGU2MzdjMTY="'
        'Content-Type': 'application/json'
        'Transfer-Encoding': 'chunked'
        'Date': 'Wed, 01 Jul 2020 09:52:21 GMT'
Response content:
{"result":[{"href":"http://192.168.10.73:8082/6.7/elements/ip_list/23139","name":"freevpn.gg","type":"ip_list"}]}
http://192.168.10.73:8082 "POST /6.7/elements/sub_ipv4_fw_policy/46/fw_ipv4_access_rule HTTP/1.1" 400 None
Request method: POST
Request URL: http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/fw_ipv4_access_rule
Request headers:
        'User-Agent': 'python-requests/2.24.0'
        'Accept-Encoding': 'gzip, deflate'
        'Accept': '*/*'
        'Connection': 'keep-alive'
        'Content-Type': 'application/json'
        'Cookie': 'JSESSIONID=2DD363BC335AF3842F8C785A0F1393DA'
        'Content-Length': '685'
Request body:
{"sources": {"any": true}, "destinations": {"dst": ["http://192.168.10.73:8082/6.7/elements/ip_list/23139"]}, "services": {"any": true}, "name": "freevpn.gg", "comment": "dies ist ein test", "action": {"action": "discard", "connection_tracking_options": {"mss_enforced": false, "mss_enforced_max": 0, "mss_enforced_min": 0, "timeout": -1}, "scan_detection": "undefined"}, "options": {"log_accounting_info_mode": false, "log_closing_mode": true, "log_level": "undefined", "log_payload_additionnal": false, "log_payload_excerpt": false, "log_payload_record": false, "log_severity": -1}, "authentication_options": {"methods": [], "require_auth": false, "users": []}, "is_disabled": false}
Response status: 400
Response headers:
        'Content-Type': 'application/json'
        'Transfer-Encoding': 'chunked'
        'Date': 'Wed, 01 Jul 2020 09:52:21 GMT'
        'Connection': 'close'
Response content:
{"details":["Invalid JSON format: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token at [line: 1, column: 213] (from: FWRuleActionDTO[\"action\"])."],"status":0}
Traceback (most recent call last):
  File "avency-blockctl.py", line 154, in <module>
    Blockctl()   
  File "avency-blockctl.py", line 146, in __init__
    self.apply_blacklists(config, args)
  File "avency-blockctl.py", line 126, in apply_blacklists
    policy.fw_ipv4_access_rules.create(name=bl['name'], services='any', sources='any', destinations=[smc.elements.network.IPList(bl['name'])], action='discard', comment=bl['comment'])
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/policy/rule.py", line 570, in create
    return ElementCreator(
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/base/decorators.py", line 103, in run
    return function(cls, json, **kwargs)
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/base/model.py", line 115, in ElementCreator
    result = SMCRequest(
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/api/common.py", line 66, in create
    return self._make_request(method='POST')
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/api/common.py", line 101, in _make_request
    raise err
smc.api.exceptions.CreateRuleFailed: Invalid JSON format: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token at [line: 1, column: 213] (from: FWRuleActionDTO["action"]).
Resetting dropped connection: 192.168.10.73
http://192.168.10.73:8082 "PUT /6.7/logout HTTP/1.1" 204 0
Logged out admin: Christian R. (Superuser) of domain: Shared Domain successfully
Call counters: Counter({'read': 6, 'create': 3, 'update': 0, 'delete': 0, 'cache': 0})
```

You can see my function call in the stacktrace:
```python
policy.fw_ipv4_access_rules.create(name=bl['name'], services='any', sources='any', destinations=[smc.elements.network.IPList(bl['name'])], action='discard', comment=bl['comment'])
```

During error it has been initialized correctly as you can see in the REST request:
```json
{"sources": {"any": true}, "destinations": {"dst": ["http://192.168.10.73:8082/6.7/elements/ip_list/23139"]}, "services": {"any": true}, "name": "freevpn.gg", "comment": "dies ist ein test", "action": {"action": "discard", "connection_tracking_options": {"mss_enforced": false, "mss_enforced_max": 0, "mss_enforced_min": 0, "timeout": -1}, "scan_detection": "undefined"}, "options": {"log_accounting_info_mode": false, "log_closing_mode": true, "log_level": "undefined", "log_payload_additionnal": false, "log_payload_excerpt": false, "log_payload_record": false, "log_severity": -1}, "authentication_options": {"methods": [], "require_auth": false, "users": []}, "is_disabled": false}
```

`"action": {"action": "discard"...` should be the correct Action name, right?
I have checked the `rules.py` file in the SMC-python project and it clearly states that `discard` is a valid operation.
Is this a bug with python 3.8.0?

**Comment by shibumi** [comment]
Mhh ok definitely not python related.. with python2.7 I get the type of same error.

**Comment by shibumi** [comment]
Oh and when I try to use a list of strings.. aka: `action=['discard']` I get this:
```
Action specified is not valid for this 'smc.api.exceptions.CreateRuleFailed: Action specified is not valid for this rule type; action: ['discard']
```

```
Response status: 202
Response headers:
        'Content-Length': '0'
        'Date': 'Wed, 01 Jul 2020 10:14:37 GMT'
Response content:

http://192.168.10.73:8082 "GET /6.7/elements?filter=avency-blockctl&filter_context=sub_ipv4_fw_policy&exact_match=True HTTP/1.1" 200 None
Request method: GET
Request URL: http://192.168.10.73:8082/6.7/elements?filter=avency-blockctl&filter_context=sub_ipv4_fw_policy&exact_match=True
Request headers:
        'User-Agent': 'python-requests/2.24.0'
        'Accept-Encoding': 'gzip, deflate'
        'Accept': '*/*'
        'Connection': 'keep-alive'
        'Content-Type': 'application/json'
        'Cookie': 'JSESSIONID=9FA8DAA33162ABCD39740596EB522F99'
Request body:
None
Response status: 200
Response headers:
        'ETag': '"ZjRiODgxZGJkNGQzZWJmZTEzMzU3Y2MwYTI3ZTgwYmU="'
        'Content-Type': 'application/json'
        'Transfer-Encoding': 'chunked'
        'Date': 'Wed, 01 Jul 2020 10:14:37 GMT'
Response content:
{"result":[{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46","name":"avency-blockctl","type":"sub_ipv4_fw_policy"}]}
http://192.168.10.73:8082 "GET /6.7/elements/sub_ipv4_fw_policy/46 HTTP/1.1" 200 None
Request method: GET
Request URL: http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46
Request headers:
        'User-Agent': 'python-requests/2.24.0'
        'Accept-Encoding': 'gzip, deflate'
        'Accept': '*/*'
        'Connection': 'keep-alive'
        'Content-Type': 'application/json'
        'Cookie': 'JSESSIONID=9FA8DAA33162ABCD39740596EB522F99'
Request body:
None
Response status: 200
Response headers:
        'Cache-Control': 'no-transform, max-age=0'
        'ETag': '"NDY5NzExNTkzNTI1MjgwNDQ0"'
        'Content-Type': 'application/json'
        'Transfer-Encoding': 'chunked'
        'Date': 'Wed, 01 Jul 2020 10:14:37 GMT'
Response content:
{"key":46,"link":[{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46","rel":"self","type":"sub_ipv4_fw_policy"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/export","rel":"export"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/history","rel":"history"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/search_category_tags_from_element","rel":"search_category_tags_from_element"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/duplicate","rel":"duplicate"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/force_unlock","rel":"force_unlock"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/search_rule","rel":"search_rule"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/open","rel":"open"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/save","rel":"save"},{"href":"http://192.168.10.73:8082/6.7/elements/sub_ipv4_fw_policy/46/fw_ipv4_access_rule","rel":"fw_ipv4_access_rules","type":"fw_ipv4_access_rule"}],"name":"avency-blockctl","read_only":false,"system":false,"system_key":-1}
http://192.168.10.73:8082 "GET /6.7/elements?filter=freevpn.gg&filter_context=ip_list&exact_match=True HTTP/1.1" 200 None
Request method: GET
Request URL: http://192.168.10.73:8082/6.7/elements?filter=freevpn.gg&filter_context=ip_list&exact_match=True
Request headers:
        'User-Agent': 'python-requests/2.24.0'
        'Accept-Encoding': 'gzip, deflate'
        'Accept': '*/*'
        'Connection': 'keep-alive'
        'Content-Type': 'application/json'
        'Cookie': 'JSESSIONID=9FA8DAA33162ABCD39740596EB522F99'
Request body:
None
Response status: 200
Response headers:
        'ETag': '"NTQ4NDk5OWViNDVlZTdhYTY4ODliODFlOGU2MzdjMTY="'
        'Content-Type': 'application/json'
        'Transfer-Encoding': 'chunked'
        'Date': 'Wed, 01 Jul 2020 10:14:37 GMT'
Response content:
{"result":[{"href":"http://192.168.10.73:8082/6.7/elements/ip_list/23139","name":"freevpn.gg","type":"ip_list"}]}
Traceback (most recent call last):
  File "avency-blockctl.py", line 154, in <module>
    Blockctl()   
  File "avency-blockctl.py", line 146, in __init__
    self.apply_blacklists(config, args)
  File "avency-blockctl.py", line 126, in apply_blacklists
    policy.fw_ipv4_access_rules.create(name=bl['name'], services='any', sources='any', destinations=[smc.elements.network.IPList(bl['name'])], action=['discard'], comment=bl['comment'])
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/policy/rule.py", line 523, in create
    raise CreateRuleFailed('Action specified is not valid for this '
smc.api.exceptions.CreateRuleFailed: Action specified is not valid for this rule type; action: ['discard']
http://192.168.10.73:8082 "PUT /6.7/logout HTTP/1.1" 204 0
```

**Comment by shibumi** [comment]
Hi,
Looks like this is this issue here: https://github.com/gabstopper/smc-python/issues/54

I am going to close this issue:

Fixed with using gabstopper/smc-python and develop branch.

It would be cool if you guys could set a new version soon and make this repository the official one. Right now I feel like jumping between two repositories.
