### ISSUE TITLE
smc.api.exceptions.CreateElementFailed: No message returned from SMC server

### ISSUE THREAD

**Issue by shibumi** [Forcepoint/fp-NGFW-SMC-python#6]
Hi,
While trying a new Firewall subpolicy I get this error message here:

```
Using SMC API version: 6.7
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chris/.vscode-oss/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/chris/.vscode-oss/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/chris/.vscode-oss/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chris/avency/avency-blockctl/avency-blockctl.py", line 247, in <module>
    Blockctl()   
  File "/home/chris/avency/avency-blockctl/avency-blockctl.py", line 238, in __init__
    self.apply_blocklists(config, args)
  File "/home/chris/avency/avency-blockctl/avency-blockctl.py", line 180, in apply_blocklists
    policy = smc.policy.layer3.FirewallSubPolicy.create('avency-blockctl')
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/policy/layer3.py", line 189, in create
    return ElementCreator(cls, json={'name': name})
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/base/decorators.py", line 103, in run
    return function(cls, json, **kwargs)
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/base/model.py", line 115, in ElementCreator
    result = SMCRequest(
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/api/common.py", line 66, in create
    return self._make_request(method='POST')
  File "/home/chris/.virtualenvs/avency-blockctl/lib/python3.8/site-packages/smc/api/common.py", line 101, in _make_request
    raise err
smc.api.exceptions.CreateElementFailed: No message returned from SMC server
Logout status was unexpected. Received response with status code: 500
```

API Version is: "6.7"
Python 3.8
I tested this with the latest tag from this repo and the develop branch from @gabstopper 

`No message returned from SMC server` is not very verbose.. is this maybe a permission problem?

**Comment by ggrimaux** [comment]
Hello,

Usually when SMC API return error code 500 it means internal error on server side. 
You should check management server traces and see if it helps you to understand the problem.

BR,
/Greg.
